// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brag_tags.sql

package queries

import (
	"context"
)

const attachTagToBrag = `-- name: AttachTagToBrag :exec
INSERT INTO brag_tags (brag_id, tag_id)
VALUES (?, ?)
`

type AttachTagToBragParams struct {
	BragID int64 `db:"brag_id" json:"brag_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) AttachTagToBrag(ctx context.Context, arg AttachTagToBragParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToBrag, arg.BragID, arg.TagID)
	return err
}

const countBragsByTag = `-- name: CountBragsByTag :one
SELECT COUNT(*) FROM brag_tags WHERE tag_id = ?
`

func (q *Queries) CountBragsByTag(ctx context.Context, tagID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBragsByTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detachAllTagsFromBrag = `-- name: DetachAllTagsFromBrag :exec
DELETE FROM brag_tags WHERE brag_id = ?
`

func (q *Queries) DetachAllTagsFromBrag(ctx context.Context, bragID int64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromBrag, bragID)
	return err
}

const detachTagFromAllBrags = `-- name: DetachTagFromAllBrags :exec
DELETE FROM brag_tags WHERE tag_id = ?
`

func (q *Queries) DetachTagFromAllBrags(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, detachTagFromAllBrags, tagID)
	return err
}

const detachTagFromBrag = `-- name: DetachTagFromBrag :exec
DELETE FROM brag_tags WHERE brag_id = ? AND tag_id = ?
`

type DetachTagFromBragParams struct {
	BragID int64 `db:"brag_id" json:"brag_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) DetachTagFromBrag(ctx context.Context, arg DetachTagFromBragParams) error {
	_, err := q.db.ExecContext(ctx, detachTagFromBrag, arg.BragID, arg.TagID)
	return err
}
