// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_titles.sql

package queries

import (
	"context"
	"database/sql"
)

const countBragsByJobTitle = `-- name: CountBragsByJobTitle :one
SELECT COUNT(*) FROM brags WHERE job_title_id = ?
`

func (q *Queries) CountBragsByJobTitle(ctx context.Context, jobTitleID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBragsByJobTitle, jobTitleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobTitle = `-- name: CreateJobTitle :one
INSERT INTO job_titles (user_id, title, company, start_date, end_date, created_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, user_id, title, company, start_date, end_date, created_at, updated_at
`

type CreateJobTitleParams struct {
	UserID    int64          `db:"user_id" json:"user_id"`
	Title     string         `db:"title" json:"title"`
	Company   sql.NullString `db:"company" json:"company"`
	StartDate sql.NullTime   `db:"start_date" json:"start_date"`
	EndDate   sql.NullTime   `db:"end_date" json:"end_date"`
}

func (q *Queries) CreateJobTitle(ctx context.Context, arg CreateJobTitleParams) (JobTitle, error) {
	row := q.db.QueryRowContext(ctx, createJobTitle,
		arg.UserID,
		arg.Title,
		arg.Company,
		arg.StartDate,
		arg.EndDate,
	)
	var i JobTitle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobTitle = `-- name: DeleteJobTitle :exec
DELETE FROM job_titles WHERE id = ?
`

func (q *Queries) DeleteJobTitle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJobTitle, id)
	return err
}

const getActiveJobTitle = `-- name: GetActiveJobTitle :one
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM job_titles 
WHERE user_id = ? AND end_date IS NULL 
ORDER BY start_date DESC, created_at DESC 
LIMIT 1
`

func (q *Queries) GetActiveJobTitle(ctx context.Context, userID int64) (JobTitle, error) {
	row := q.db.QueryRowContext(ctx, getActiveJobTitle, userID)
	var i JobTitle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobTitle = `-- name: GetJobTitle :one
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM job_titles WHERE id = ? LIMIT 1
`

func (q *Queries) GetJobTitle(ctx context.Context, id int64) (JobTitle, error) {
	row := q.db.QueryRowContext(ctx, getJobTitle, id)
	var i JobTitle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobTitleByName = `-- name: GetJobTitleByName :one
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM job_titles 
WHERE user_id = ? AND title = ? 
ORDER BY start_date DESC, created_at DESC 
LIMIT 1
`

type GetJobTitleByNameParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	Title  string `db:"title" json:"title"`
}

func (q *Queries) GetJobTitleByName(ctx context.Context, arg GetJobTitleByNameParams) (JobTitle, error) {
	row := q.db.QueryRowContext(ctx, getJobTitleByName, arg.UserID, arg.Title)
	var i JobTitle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobTitlesByUser = `-- name: ListJobTitlesByUser :many
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM job_titles
WHERE user_id = ?
ORDER BY CASE WHEN start_date IS NULL THEN 1 ELSE 0 END, start_date DESC, created_at DESC
`

func (q *Queries) ListJobTitlesByUser(ctx context.Context, userID int64) ([]JobTitle, error) {
	rows, err := q.db.QueryContext(ctx, listJobTitlesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTitle
	for rows.Next() {
		var i JobTitle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Company,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobTitle = `-- name: UpdateJobTitle :one
UPDATE job_titles
SET title = ?, company = ?, start_date = ?, end_date = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, company, start_date, end_date, created_at, updated_at
`

type UpdateJobTitleParams struct {
	Title     string         `db:"title" json:"title"`
	Company   sql.NullString `db:"company" json:"company"`
	StartDate sql.NullTime   `db:"start_date" json:"start_date"`
	EndDate   sql.NullTime   `db:"end_date" json:"end_date"`
	ID        int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateJobTitle(ctx context.Context, arg UpdateJobTitleParams) (JobTitle, error) {
	row := q.db.QueryRowContext(ctx, updateJobTitle,
		arg.Title,
		arg.Company,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i JobTitle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
