// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package queries

import (
    "context"
    "database/sql"
)

const countBragsByPosition = `-- name: CountBragsByPosition :one
-- :param position_id int64
SELECT COUNT(*) FROM brags WHERE position_id = ?
`

func (q *Queries) CountBragsByPosition(ctx context.Context, positionID int64) (int64, error) {
    row := q.db.QueryRowContext(ctx, countBragsByPosition, positionID)
    var count int64
    err := row.Scan(&count)
    return count, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (user_id, title, company, start_date, end_date, created_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, user_id, title, company, start_date, end_date, created_at, updated_at
`

type CreatePositionParams struct {
    UserID    int64        `db:"user_id" json:"user_id"`
    Title     string       `db:"title" json:"title"`
    Company   string       `db:"company" json:"company"`
    StartDate sql.NullTime `db:"start_date" json:"start_date"`
    EndDate   sql.NullTime `db:"end_date" json:"end_date"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
    row := q.db.QueryRowContext(ctx, createPosition,
        arg.UserID,
        arg.Title,
        arg.Company,
        arg.StartDate,
        arg.EndDate,
    )
    var i Position
    err := row.Scan(
        &i.ID,
        &i.UserID,
        &i.Title,
        &i.Company,
        &i.StartDate,
        &i.EndDate,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = ?
`

func (q *Queries) DeletePosition(ctx context.Context, id int64) error {
    _, err := q.db.ExecContext(ctx, deletePosition, id)
    return err
}

const getPosition = `-- name: GetPosition :one
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM positions WHERE id = ? LIMIT 1
`

func (q *Queries) GetPosition(ctx context.Context, id int64) (Position, error) {
    row := q.db.QueryRowContext(ctx, getPosition, id)
    var i Position
    err := row.Scan(
        &i.ID,
        &i.UserID,
        &i.Title,
        &i.Company,
        &i.StartDate,
        &i.EndDate,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}

const listPositionsByUser = `-- name: ListPositionsByUser :many
SELECT id, user_id, title, company, start_date, end_date, created_at, updated_at FROM positions
WHERE user_id = ?
ORDER BY CASE WHEN start_date IS NULL THEN 1 ELSE 0 END, start_date DESC, created_at DESC
`

func (q *Queries) ListPositionsByUser(ctx context.Context, userID int64) ([]Position, error) {
    rows, err := q.db.QueryContext(ctx, listPositionsByUser, userID)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    var items []Position
    for rows.Next() {
        var i Position
        if err := rows.Scan(
            &i.ID,
            &i.UserID,
            &i.Title,
            &i.Company,
            &i.StartDate,
            &i.EndDate,
            &i.CreatedAt,
            &i.UpdatedAt,
        ); err != nil {
            return nil, err
        }
        items = append(items, i)
    }
    if err := rows.Close(); err != nil {
        return nil, err
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET title = ?, company = ?, start_date = ?, end_date = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, company, start_date, end_date, created_at, updated_at
`

type UpdatePositionParams struct {
    Title     string       `db:"title" json:"title"`
    Company   string       `db:"company" json:"company"`
    StartDate sql.NullTime `db:"start_date" json:"start_date"`
    EndDate   sql.NullTime `db:"end_date" json:"end_date"`
    ID        int64        `db:"id" json:"id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
    row := q.db.QueryRowContext(ctx, updatePosition,
        arg.Title,
        arg.Company,
        arg.StartDate,
        arg.EndDate,
        arg.ID,
    )
    var i Position
    err := row.Scan(
        &i.ID,
        &i.UserID,
        &i.Title,
        &i.Company,
        &i.StartDate,
        &i.EndDate,
        &i.CreatedAt,
        &i.UpdatedAt,
    )
    return i, err
}
