// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	AttachTagToBrag(ctx context.Context, arg AttachTagToBragParams) error
	CountBragsByTag(ctx context.Context, tagID int64) (int64, error)
	CreateBrag(ctx context.Context, arg CreateBragParams) (Brag, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBrag(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DetachAllTagsFromBrag(ctx context.Context, bragID int64) error
	DetachTagFromAllBrags(ctx context.Context, tagID int64) error
	DetachTagFromBrag(ctx context.Context, arg DetachTagFromBragParams) error
	GetBrag(ctx context.Context, id int64) (Brag, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListBragsByCategory(ctx context.Context, arg ListBragsByCategoryParams) ([]Brag, error)
	ListBragsByUser(ctx context.Context, ownerID int64) ([]Brag, error)
	ListTagsByBrag(ctx context.Context, bragID int64) ([]Tag, error)
	ListTagsByUser(ctx context.Context, ownerID int64) ([]Tag, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchBragsByTags(ctx context.Context, arg SearchBragsByTagsParams) ([]Brag, error)
	UpdateBrag(ctx context.Context, arg UpdateBragParams) (Brag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
