// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	AttachTagToBrag(ctx context.Context, arg AttachTagToBragParams) error
	CountBragsByCategory(ctx context.Context, categoryID int64) (int64, error)
	CountBragsByJobTitle(ctx context.Context, jobTitleID sql.NullInt64) (int64, error)
	CountBragsByTag(ctx context.Context, tagID int64) (int64, error)
	CreateBrag(ctx context.Context, arg CreateBragParams) (Brag, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateJobTitle(ctx context.Context, arg CreateJobTitleParams) (JobTitle, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBrag(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteJobTitle(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DetachAllTagsFromBrag(ctx context.Context, bragID int64) error
	DetachTagFromAllBrags(ctx context.Context, tagID int64) error
	DetachTagFromBrag(ctx context.Context, arg DetachTagFromBragParams) error
	GetActiveJobTitle(ctx context.Context, userID int64) (JobTitle, error)
	GetBrag(ctx context.Context, id int64) (Brag, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetJobTitle(ctx context.Context, id int64) (JobTitle, error)
	GetJobTitleByName(ctx context.Context, arg GetJobTitleByNameParams) (JobTitle, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListBragsByCategory(ctx context.Context, arg ListBragsByCategoryParams) ([]Brag, error)
	ListBragsByUser(ctx context.Context, ownerID int64) ([]Brag, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListJobTitlesByUser(ctx context.Context, userID int64) ([]JobTitle, error)
	ListTagsByBrag(ctx context.Context, bragID int64) ([]Tag, error)
	ListTagsByUser(ctx context.Context, ownerID int64) ([]Tag, error)
	ListUsers(ctx context.Context) ([]User, error)
	SearchBragsByTags(ctx context.Context, arg SearchBragsByTagsParams) ([]Brag, error)
	UpdateBrag(ctx context.Context, arg UpdateBragParams) (Brag, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateJobTitle(ctx context.Context, arg UpdateJobTitleParams) (JobTitle, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
