// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package queries

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, owner_id, created_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
RETURNING id, name, owner_id, created_at
`

type CreateTagParams struct {
	Name    string `db:"name" json:"name"`
	OwnerID int64  `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.OwnerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, owner_id, created_at FROM tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, owner_id, created_at FROM tags WHERE owner_id = ? AND name = ? LIMIT 1
`

type GetTagByNameParams struct {
	OwnerID int64  `db:"owner_id" json:"owner_id"`
	Name    string `db:"name" json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, arg.OwnerID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByBrag = `-- name: ListTagsByBrag :many
SELECT t.id, t.name, t.owner_id, t.created_at FROM tags t
JOIN brag_tags bt ON t.id = bt.tag_id
WHERE bt.brag_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByBrag(ctx context.Context, bragID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByBrag, bragID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, name, owner_id, created_at FROM tags WHERE owner_id = ? ORDER BY name ASC
`

func (q *Queries) ListTagsByUser(ctx context.Context, ownerID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
