version: "2"

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - goconst
    - gocyclo
    - dupl
    - misspell
    - unparam
    - unconvert
    - prealloc
    - bodyclose
    - noctx
    - nilerr

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
