name: quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency: pipeline-quality

jobs:
  pipeline-quality:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-go@v5
        name: setup-go
        with:
          go-version: '1.25'

      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.50.1
          args: --issues-exit-code=0 --timeout 3m0s
          only-new-issues: true
          skip-cache: true

      - name: Run tests
        run: |
          go mod tidy
          go test ./... -v -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
