name: quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency: pipeline-quality

jobs:
  pipeline-quality:
    runs-on: [ self-hosted, buildstaging-iac ]
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-go@v4
        name: setup-go
        with:
          go-version: 1.21

      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --issues-exit-code=0 --timeout 3m0s
          only-new-issues: true
          skip-cache: true
      - name: Run-test
        run: |
          go mod tidy
          go test ./...
